- name: conditions
  hosts: local
  connection: local
  vars:
    NUMBER: 78
  tasks: 
  - name: print if numvber is less than 100
    ansible.builtin.debug:
      msg: "Given number si s{{ NUMBER }} is less than 100"
    when: NUMBER < 100

  - name: print if numvber is greater than 100
    ansible.builtin.debug:
      msg: "Given number si s{{ NUMBER }} is greater than 100"
    when: NUMBER > 100



