- name: functions
  hosts: local
  connection: local
  vars:
    persons: "kiran,mehar,suresh,ramesh"
  tasks:
  - name: giving default functions
    ansible.builtin.debug:
      #msg: "Hello ,{{ person | default('ramesh') }} " #by adding default person ramesh so that in person field the name will be ramesh
      msg: "Hello , {{ number | default('22')}}"

  - name: printing persons
    ansible.builtin.debug:
      msg: "Hello {{ persons }}"
  

  - name: printing persons
    ansible.builtin.debug:
      msg: "Hello persons = {{ persons  | split(',') }}"
 

  - name: course information
    vars:
      course:
        duration : 10hr
        trainer: meharsai
        language: java
    ansible.builtin.debug:
      msg: COURSE INFO : "{{ course | dict2items }}"





    


  