- name: functions
  hosts: local
  connection: local
  vars:
    persons: "kiran,mehar,suresh,ramesh"
  tasks:
  - name: giving default functions
    ansible.builtin.debug:
      #msg: "Hello ,{{ person | default('ramesh') }} " #by adding default person ramesh so that in person field the name will be ramesh
      msg: "Hello , {{ number | default('22')}}"

  - name: printing persons
    ansible.builtin.debug:
      msg: "Hello {{ persons }}"
  

  - name: printing persons
    ansible.builtin.debug:
      msg: "Hello persons = {{ persons  | split(',') }}"
 

  - name: course information
    vars:
      course:
        duration : 10hr
        trainer: meharsai
        language: java
    ansible.builtin.debug:
      msg: " COURSE INFO : {{ course | dict2items }}"


  - name: course desription
    vars:
      course:
       - {'key': 'duration', 'value': '10hr'}
       - {'key': 'trainer', 'value': 'meharsai'}
       - {'key': 'language', 'value': 'java'}

    ansible.builtin.debug:
      msg: "COURSE DESCRIPTION : {{course | items2dict}}"


  - name: Lower to upper
    vars:
      NAME:
        r.meharsai
    ansible.builtin.debug:
      msg: "My name is : {{ NAME | upper }}"

  - name: Upper to Lower
    vars:
      NAME: 
        R.meharsai
    ansible.builtin.debug:
      msg: "My name is : {{NAME | lower}}"

  - name: Whether the ip address is fake or real
    vars:
      IP:
        192.167.23.1
    ansible.builtin.debug:
      msg: "Ip address is :: {{IP | ansible.utils.ipaddr }}"

  - name: Whether the ip is fake or real
    vars:
      IP:
        255.2556.345.654
    ansible.builtin.debug:
      msg: "The ip address is :: {{IP | ansible.utils,ipaddr}}"






    


  