- name: installing multiple packages
  hosts: frontend
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - mysql
      - zip
