- name: install nginx and run
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present



  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes


- name: install python3
  hosts: frontend
  become: yes
  tasks:
  - name: install python3 and run
    ansible.builtin.package:
      name: python3
      state: present


  - name: start python3
    ansible.builtin.service:
      name: python3
      state: started
      enabled: yes