- name: install nginx
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      service: present



  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started 
      enable: yes