- name: prompt user name and password
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Enter your username
    private: false

  - name: PASSWORD
    prompt: Enter your password
    private: false

  tasks:
  - name: Username and password information
    ansible.builtin.debug:
      msg: "username is {{USERNAME}} and password is {{PASSWORD}}"