- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: Devops
    DURATION: 15HR
    TRAINER: mehar sai

  tasks:
  - name: Printing course details
    ansible.builtin.debug:
      msg: "Trainer is: {{ TRAINER }}, course is: {{COURSE}}, Duration is: {{DURATION}} "

  - name: printing devops other course
    vars:
      TRAINER: Saiteja
    ansible.builtin.debug:
      msg: "Trainer is: {{ TRAINER }}, course is: {{COURSE}}, Duration is: {{DURATION}} "



- name: printing java course details
  hosts: local
  connection: local
  vars:
    trainer: mehar
    teachingmode: online
    time: daily 1 hour

  tasks:
  - name: java course details
    ansible.builtin.debug:
      msg: "trainer is {{trainer}}, time is {{time}} ,teachingmode is {{teachingmode}}"
   