- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: Devops
    DURATION: 15HR
    TRAINER: mehar sai

  tasks:
  - name: Printing course details
    ansible.builtin.debug:
      msg: "Trainer is: {{ TRAINER }}, course is: {{COURSE}}, Duration is: {{DURATION}} "