- name: calling variables from inventory
  hosts: frontend
  vars_prompt:
  - name: USERNAME
    prompt: Enter your username
    private: true
  tasks:
  - name: course information
    ansible.builtin.debug:
      msg: "course is: {{COURSE}}, Duration is {{DURATION}}, Trainer is: {{TRAINER}}"