- name: variables preferences
  hosts: local
  connection: local
  # vars:
  #   GREETING: Hello from playbook
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREETING
  #   prompt: please enter the greeting
  #   private: false
  tasks:
  - name: print the preference variable types
    # vars:
    #   GREETING: Hello from task level
    ansible.builtin.debug:
      msg: "{{GREETING}}"



#1= i have added something in commandline at lost the args will be executed 
#2= the task level variable will be executed
#3= the files variable is executed
#4= prompt will be executed
#5= The playbook means the gobal one or the variable whole code at starting is executed after prompt
#6= at last inventory variable is executed