- name: when condition
  hosts: local
  connection: local
  vars_prompt:
  - name: THE_NUMBER
    prompt: Enter the NUMBER
    private: false
  tasks:
  - name: The number is less than or equal to 100
    ansible.builtin.debug:
      msg: "{{THE_NUMBER}} is less than or equal to 100"
    when: THE_NUMBER <= 100

  - name: The number is greater than 100
    ansible.builtin.debug:
      msg: " {{THE_NUMBER}} is greater than 100"
    when: THE_NUMBER > 100
    